development:
    adapter: mysql2
    host: localhost
    username: root
    password:
    database: entry_comment_development
    encoding: utf8

test:
    adapter: mysql2
    host: localhost
    username: root
    password:
    encoding: utf8
    database: entry_comment_test

production:
    adapter: mysql2
    encoding: unicode
    database: entry_comment_production
    pool: 5
