development:
    adapter: mysql2
    host: localhost
    username: root
    password:
    database: hello_scaffold_development
    encoding: utf8

test:
    adapter: mysql2
    host: localhost
    username: root
    password:
    encoding: utf8
    database: hello_scaffold_test

production:
    adapter: mysql2
    encoding: unicode
    database: hello_scaffold_production
    pool: 5
